// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/coordpb/coordinator.proto

package coordpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoadgenControl_UpdateActiveServers_FullMethodName = "/coordpb.LoadgenControl/UpdateActiveServers"
)

// LoadgenControlClient is the client API for LoadgenControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Loadgen implemented service
type LoadgenControlClient interface {
	UpdateActiveServers(ctx context.Context, in *UpdateActiveServersRequest, opts ...grpc.CallOption) (*UpdateActiveServersResponse, error)
}

type loadgenControlClient struct {
	cc grpc.ClientConnInterface
}

func NewLoadgenControlClient(cc grpc.ClientConnInterface) LoadgenControlClient {
	return &loadgenControlClient{cc}
}

func (c *loadgenControlClient) UpdateActiveServers(ctx context.Context, in *UpdateActiveServersRequest, opts ...grpc.CallOption) (*UpdateActiveServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateActiveServersResponse)
	err := c.cc.Invoke(ctx, LoadgenControl_UpdateActiveServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoadgenControlServer is the server API for LoadgenControl service.
// All implementations must embed UnimplementedLoadgenControlServer
// for forward compatibility.
//
// Loadgen implemented service
type LoadgenControlServer interface {
	UpdateActiveServers(context.Context, *UpdateActiveServersRequest) (*UpdateActiveServersResponse, error)
	mustEmbedUnimplementedLoadgenControlServer()
}

// UnimplementedLoadgenControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoadgenControlServer struct{}

func (UnimplementedLoadgenControlServer) UpdateActiveServers(context.Context, *UpdateActiveServersRequest) (*UpdateActiveServersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateActiveServers not implemented")
}
func (UnimplementedLoadgenControlServer) mustEmbedUnimplementedLoadgenControlServer() {}
func (UnimplementedLoadgenControlServer) testEmbeddedByValue()                        {}

// UnsafeLoadgenControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoadgenControlServer will
// result in compilation errors.
type UnsafeLoadgenControlServer interface {
	mustEmbedUnimplementedLoadgenControlServer()
}

func RegisterLoadgenControlServer(s grpc.ServiceRegistrar, srv LoadgenControlServer) {
	// If the following call pancis, it indicates UnimplementedLoadgenControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoadgenControl_ServiceDesc, srv)
}

func _LoadgenControl_UpdateActiveServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateActiveServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadgenControlServer).UpdateActiveServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadgenControl_UpdateActiveServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadgenControlServer).UpdateActiveServers(ctx, req.(*UpdateActiveServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoadgenControl_ServiceDesc is the grpc.ServiceDesc for LoadgenControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoadgenControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coordpb.LoadgenControl",
	HandlerType: (*LoadgenControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateActiveServers",
			Handler:    _LoadgenControl_UpdateActiveServers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coordpb/coordinator.proto",
}

const (
	ProxyControl_SetMode_FullMethodName = "/coordpb.ProxyControl/SetMode"
)

// ProxyControlClient is the client API for ProxyControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service implemented by each proxy so coordinator can call SetMode
type ProxyControlClient interface {
	SetMode(ctx context.Context, in *ModeRequest, opts ...grpc.CallOption) (*ModeResponse, error)
}

type proxyControlClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyControlClient(cc grpc.ClientConnInterface) ProxyControlClient {
	return &proxyControlClient{cc}
}

func (c *proxyControlClient) SetMode(ctx context.Context, in *ModeRequest, opts ...grpc.CallOption) (*ModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModeResponse)
	err := c.cc.Invoke(ctx, ProxyControl_SetMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyControlServer is the server API for ProxyControl service.
// All implementations must embed UnimplementedProxyControlServer
// for forward compatibility.
//
// Service implemented by each proxy so coordinator can call SetMode
type ProxyControlServer interface {
	SetMode(context.Context, *ModeRequest) (*ModeResponse, error)
	mustEmbedUnimplementedProxyControlServer()
}

// UnimplementedProxyControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyControlServer struct{}

func (UnimplementedProxyControlServer) SetMode(context.Context, *ModeRequest) (*ModeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMode not implemented")
}
func (UnimplementedProxyControlServer) mustEmbedUnimplementedProxyControlServer() {}
func (UnimplementedProxyControlServer) testEmbeddedByValue()                      {}

// UnsafeProxyControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyControlServer will
// result in compilation errors.
type UnsafeProxyControlServer interface {
	mustEmbedUnimplementedProxyControlServer()
}

func RegisterProxyControlServer(s grpc.ServiceRegistrar, srv ProxyControlServer) {
	// If the following call pancis, it indicates UnimplementedProxyControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyControl_ServiceDesc, srv)
}

func _ProxyControl_SetMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyControlServer).SetMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyControl_SetMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyControlServer).SetMode(ctx, req.(*ModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyControl_ServiceDesc is the grpc.ServiceDesc for ProxyControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coordpb.ProxyControl",
	HandlerType: (*ProxyControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetMode",
			Handler:    _ProxyControl_SetMode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coordpb/coordinator.proto",
}

const (
	Coordinator_NotifyState_FullMethodName = "/coordpb.Coordinator/NotifyState"
)

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service implemented by the coordinator so proxies can send notifications
type CoordinatorClient interface {
	NotifyState(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
}

type coordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorClient(cc grpc.ClientConnInterface) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) NotifyState(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, Coordinator_NotifyState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServer is the server API for Coordinator service.
// All implementations must embed UnimplementedCoordinatorServer
// for forward compatibility.
//
// Service implemented by the coordinator so proxies can send notifications
type CoordinatorServer interface {
	NotifyState(context.Context, *NotifyRequest) (*NotifyResponse, error)
	mustEmbedUnimplementedCoordinatorServer()
}

// UnimplementedCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServer struct{}

func (UnimplementedCoordinatorServer) NotifyState(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyState not implemented")
}
func (UnimplementedCoordinatorServer) mustEmbedUnimplementedCoordinatorServer() {}
func (UnimplementedCoordinatorServer) testEmbeddedByValue()                     {}

// UnsafeCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServer will
// result in compilation errors.
type UnsafeCoordinatorServer interface {
	mustEmbedUnimplementedCoordinatorServer()
}

func RegisterCoordinatorServer(s grpc.ServiceRegistrar, srv CoordinatorServer) {
	// If the following call pancis, it indicates UnimplementedCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Coordinator_ServiceDesc, srv)
}

func _Coordinator_NotifyState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).NotifyState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_NotifyState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).NotifyState(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Coordinator_ServiceDesc is the grpc.ServiceDesc for Coordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coordpb.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyState",
			Handler:    _Coordinator_NotifyState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coordpb/coordinator.proto",
}
